server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/
      routes:
        # ===================
        - id: login
          uri: lb://login
          predicates:
            - Path=/login/**
        # ===================
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**