server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/
      routes:
        # ===================
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
        # ===================
        - id: accounts
          uri: lb://accounts
          predicates:
            - Path=/accounts/**