server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - PrefixPath=/
      routes:
        #---------
        - id: transactions
          uri: lb://transactions
          predicates:
            - Path=/transactions/**
        #---------
        - id: bank-accounts
          uri: lb://bank-accounts
          predicates:
            - Path=/accounts/**
        # ===================
        - id: user-access
          uri: lb://user-access
          predicates:
            - Path=/users/**
#        # ===================
#        - id: accounts
#          uri: lb://accounts
#          predicates:
#            - Path=/accounts/**
